server:
  port: 8086

spring:
  mvc:
    servlet:
      path: /api/v1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      # Каналы для Pub/Sub механизма Redis
      channels:
        comment-event: "app:comment:created"
        follower-event: "app:user:follower-added"
        like-event: "app:post:liked"
        post-view-event: "app:post:viewed"
        premium-bought-event: "app:user:premium-purchased"
        profile-appeared-in-search-event: "app:user:profile:appeared-in-search"
        profile-view-event: "app:user:profile:viewed"

  task:
    execution:
      pool:
        core-size: 10
        max-size: 50
        queue-capacity: 100
        threadNamePrefix: "RedisExecutor-"

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082